### ISSUE TITLE
Error: Failure reading input file 

### ISSUE THREAD

**Issue by LoayJabre** [mhoopmann/hardklor#11]
Hi - 

I'm trying to use Hardklor on a linux machine, and I get the following error when I run it: 

ljabre@Doris:~/projects/hardklorporgram$ ../hardklorporgram/hardklor Hardklor.conf 
Hardklor v2.3.0, August 14 2015
Mike Hoopmann, Mike MacCoss
Copyright 2007-2015
University of Washington
Reading from file: 220718_1082_097_BSA10_90.mzML
Writing to file: 220718_1082_097_BSA10_90.hk
No index list offset found. File will not be read.
ERROR: Failure reading input file 220718_1082_097_BSA10_90.mzML
220718_1082_097_BSA10_90.mzML is invalid, or contains no spectrum.

I get the same error if I try to use a .raw file. 

Do you have any tips on getting this to work ?

**Comment by mhoopmann** [comment]
Hi Loay,
Yes, the problem is that your mzML file is missing its index. This can be resolved using a converter that can index the mzML file (as per the current standard). Recommended converters are msconvert from ProteoWizard (https://proteowizard.sourceforge.io/), and ThermoRawFileParser (https://github.com/compomics/ThermoRawFileParser) using the --format=2 option.

Let me know if that resolves the issue. If not, we'll go the more difficult route of setting you up with software that can add an index to an mzML file.

Cheers,
Mike

**Comment by LoayJabre** [comment]
Thanks Mike! I used ThermoRawFileParser to convert the raw files into indexed mzMLs and it worked perfectly! 

Just out of curiosity, why won't Hardklor work with raw files work on Linux, but can use them on Windows ?

**Comment by mhoopmann** [comment]
Great, glad that solved the problem. Hardklor can only read raw files on Windows because, at the time of its development, Thermo libraries for file reading only existed on Windows. To make use of them, you would have to install Xcalibur on the same computer as your Hardklor. 

Today there is a ThermoRawFileReader library for C# that allows raw file reading on Linux boxes, but there hasn't been the resources or demand to mate the two source codes.
