### ISSUE TITLE
Trying to process an MGF file: error says can't load Thermo RAW files

### ISSUE THREAD

**Issue by DarylWM** [mhoopmann/hardklor#4]
Hello. Thanks for sharing the code. I'm trying to run the Windows 64-bit binary on an example MGF file, but I get an error saying it can't load Thermo RAW files. I'm not asking it to (at least, I'm not intending to). Can you point me to something I'm missing?

`
...>\Hardklor-win64-2_3_0\Hardklor.exe Hardklor.conf
Hardklor v2.3.0, August 14 2015
Mike Hoopmann, Mike MacCoss
Copyright 2007-2015
University of Washington
Cannot load Thermo MSFileReader. Cannot read .RAW files.
Reading from file: test.mgf
Writing to file: test.hk
100

  Total number of scans analyzed: 2

File access time: 0 minutes, 0 seconds.
Analysis Time:    0 minutes, 0 seconds.
IMPOSSIBLE!!!
`

My config file is untouched from the download, apart from the input and output file names.

**Comment by mhoopmann** [comment]
Hi Daryl,
Sorry for the misleading warning message. It is likely caused by some old
code that checks for MSFileReader. It is a harmless message that will go
away if you install MSFileReader. It should not affect your analysis. I can
send you an update in two weeks when I return to work.
Cheers,
Mike

On Jun 9, 2017 8:48 PM, "Daryl Wilding-McBride" <notifications@github.com>
wrote:

Hello. Thanks for sharing the code. I'm trying to run the Windows 64-bit
binary on an example MGF file, but I get an error saying it can't load
Thermo RAW files. I'm not asking it to (at least, I'm not intending to).
Can you point me to something I'm missing?

`
...>\Hardklor-win64-2_3_0\Hardklor.exe Hardklor.conf
Hardklor v2.3.0, August 14 2015
Mike Hoopmann, Mike MacCoss
Copyright 2007-2015
University of Washington
Cannot load Thermo MSFileReader. Cannot read .RAW files.
Reading from file: test.mgf
Writing to file: test.hk
100

Total number of scans analyzed: 2

File access time: 0 minutes, 0 seconds.
Analysis Time: 0 minutes, 0 seconds.
IMPOSSIBLE!!!
`

My config file is untouched from the download, apart from the input and
output file names.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mhoopmann/hardklor/issues/4>, or mute the thread

**Comment by DarylWM** [comment]
Thanks for the fast response Mike. I can see now it is doing the analysis, so it's all good.
